name: emi_solution
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        
        - asset: assets/fonts/Roboto_Condensed-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
